### PR TITLE
PKCS7 improvements

### LINKED ISSUE #1: pkcs7 unpad function fails on inputs that are not valid pkcs7 encoded
https://github.com/bcelenza/cryptopals-challenges-rust/blob/492ca698c1c1aea384ca72a676abe5c2528ae042/src/pkcs7.rs#L15-L18

An input of `{0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x60,0x01,0x02,0x03,0x04,0x05}` would return `{0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x60}` instead of the original string ~~which is a valid pkcs7 string for a 16 byte block length. Unpad function should take a block length parameter in order to handle 0-padded inputs~~ (e: this is incorrect, pkcs7 rfc requires a full block of padding; a 0-padded string is not a valid result).

Should also validate that the input is a valid pkcs7 padding string by checking that all characters of the expected pad length equal.

Would not merge, 3/5. 😜 

note: this is covered here https://cryptopals.com/sets/2/challenges/15

### PR DESCRIPTION
**Pull request by drmille2**
Updates the PKCS7 `unpad()` function to perform input validation and raise a new `Pkcs7UnpadError` if the input is not properly formatted PKCS7. Updates usages of the function to provide the appropriate block_size input and handle the new `Result<>` output.

Style changes to the PKCS7 `pad()` function to remove unneeded if-logic.

Fixes #1

### CODE REVIEW

File: src/pkcs7.rs [hunk 1]
```diff
@@ -1,20 +1,43 @@
...
-        } else {
-            pad_num = key_size - (input.len() % key_size);
-        }
+        pad_num = key_size - (input.len() % key_size);
         [input.to_vec(), vec![pad_num as u8; pad_num]].concat()
     }
     
-    pub fn unpad(input: &[u8]) -> Vec<u8> {
+    pub fn unpad(input: &[u8], key_size: usize) -> Result<Vec<u8>> {
         let pad_num = input.last().unwrap();
```
Comment (bcelenza) [inline src/pkcs7.rs]: Seems like it might be convenient to cast as `usize` here instead of repeatedly below?

File: src/pkcs7.rs [hunk 2]
```diff
@@ -1,20 +1,43 @@
-
 pub mod pkcs7 {
+    use std::fmt;
+    use std::error::Error;
+
+    type Result<T> = std::result::Result<T, Pkcs7UnpadError>;
```
Comment (bcelenza) [inline src/pkcs7.rs:5]: Does this provide a benefit other than making the method signature a little simpler? Trying to understand if below should just be specified as `Result<Vec<u8>, Pkcs7UnpadError>`?

File: src/pkcs7.rs [hunk 3]
```diff
@@ -51,15 +74,20 @@ pub mod pkcs7 {
         #[test]
         fn test_unpad_single_byte() {
             let input = vec![0, 0, 0, 1];
-            let result = unpad(&input);
-            assert_eq!(vec![0, 0, 0], result);
+            match unpad(&input, 4) {
+                Ok(v) => assert_eq!(vec![0, 0, 0], v),
+                Err(e) => panic!("{}", e)
+            }
```
Comment (bcelenza) [inline src/pkcs7.rs]: In the successful assertion instances I think we can write it as:

```rust
let result = unpad(&input).unwrap();
assert_eq!(vec![0, 0, 0], result);
```

But given the guidance [here](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap) I'm learning its only if you _want_ a runtime panic as a result of `Err`. I'm probably using `unwrap` elsewhere and shouldn't be.

**Comment by bcelenza** [comment]
Nice catch! Appreciate the error handling addition as well, I don't think I've done a custom error in rust yet so I learned something.

Could we add a test for the new `Err` functionality on `pkcs7::unpad`?

File: src/pkcs7.rs (hunk 2 above)
Comment (drmille2) [reply src/pkcs7.rs:5]: Honestly, not sure, I was a bit fuzzy on what was the recommended approach to defining results types for rust. I have no objection with using literals though.

File: src/pkcs7.rs (hunk 3 above)
Comment (drmille2) [reply src/pkcs7.rs]: Ah, so that's what the unwrap() is doing, that makes a lot more sense now.

**Review by bcelenza — APPROVED** [review]
